version: '3'

services:
  db:
    build:
      context: ./mysql
    tty: true
    command: --innodb-use-native-aio=0
    restart: always
    networks:
      - fullcycle-net
    volumes:
      - db-vol:/var/lib/mysql
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=fullcycle
      - MYSQL_DATABASE=cadastro
  api:
    build:
      context: ./node
    container_name: node-server
    tty: true
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./node:/src/api
    networks:
      - fullcycle-net
    depends_on:
      - db
  proxy:
    build: 
      context: ./nginx
    ports:
      - 8080:80
    container_name: nginx-server
    restart: always
    depends_on:
      - api
    networks:
      - fullcycle-net

networks:
  fullcycle-net:
    driver: bridge
volumes:
  db-vol: