version: '3'

services:
  db:
    build:
      context: ./mysql
    tty: true
    command: --innodb-use-native-aio=0
    restart: always
    networks:
      - fullcycle-net
    container_name: mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=fullcycle
      - MYSQL_DATABASE=empresa
  api:
    build:
      context: ./node
    container_name: node-server
    tty: true
    restart: always
    volumes:
      - ./node:/src/api
    networks:
      - fullcycle-net
    depends_on:
      - db
  proxy:
    build: 
      context: ./nginx
    ports:
      - 8080:80
    container_name: nginx-server
    restart: always
    depends_on:
      - api
    networks:
      - fullcycle-net

networks:
  fullcycle-net:
    driver: bridge